# --- API Keys ---
GOOGLE_API_KEY = "AIzaSyCYlQjxHPNFcpgBb0vFPbrL-Mp1C2EPDiA" 
NAVER_CLIENT_ID = "ZWTCzG83HufXAx88hmuC"    # 네이버 검색용
NAVER_CLIENT_SECRET = "YqIcGy_uvD"
SERPER_API_KEY = "57d9ef85669b168c7b81030b5d45bb698f6801a8"      # Serper(서퍼) API
TABILI_API_KEY = "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"      # Tavily(타빌리) API

# --- 데이터 경로 ---
FRANCHISE_CSV = "./data/franchise_data.csv"
BIZ_AREA_CSV = "./data/biz_area.csv"
ADMIN_DONG_CSV = "./data/admin_dong.csv"

# --- 검색 파라미터 ---
SEARCH_TIMEOUT = 12              # 초 단위
SEARCH_TOPK = 5                  # 상위 K 결과
SEARCH_RECENCY_DAYS = 60         # 최근 N일 가중/필터

# --- 정책/토글 ---
CONFIRM_ON_MULTI = 0
LLM_MODEL = "gemini-2.5-flash"
LLM_TEMPERATURE = 0.2
ENABLE_RELEVANCE_CHECK = true
ENABLE_MEMORY = true

# --- (선택) gRPC 로그 억제 ---
GRPC_VERBOSITY = "ERROR"
GRPC_TRACE = ""